### ISSUE TITLE
Runtime Transform Handles, override F12 key behaviour

### ISSUE THREAD

**Issue by BattlehubCode** [BattlehubCode/RTE_Docs#116]
When I was using it, I pressed F12 to enter editing, and I couldn't find a way to exit editing.How do I restore to the state before pressing F12?

**Comment by BattlehubCode** [comment]
Hi, I'll make it more convenient in one of the updates.

For now please use following workaround

1. Enter play mode and create RTE.prefab
![image](https://github.com/user-attachments/assets/07441e42-00a4-40b4-af0d-46405e5ce30c)

2. Exit play mode and drag & drop RTE.prefab to the scene:
3. Set SceneCamera field: 

![image](https://github.com/user-attachments/assets/cb63cc14-274f-41fe-bf45-eecca7d5514d)

4. Set OpenEditorKey to None
![image](https://github.com/user-attachments/assets/a80e6fbb-38f8-4a8d-9611-1bc5be47a835)

**Comment by weilifang25** [comment]
Thank you for your reply, but it does not solve my problem. I want to ask why I can't move the main camera? I need to find a problem in the scene, click a button, and then move the camera so that the object is in the center of the screen. Now the problem is that the camera position is fixed and cannot be changed.
